//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DBStudio 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Database 的本地化字符串。
        /// </summary>
        internal static string ButtonBackupDatabase {
            get {
                return ResourceManager.GetString("ButtonBackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string ButtonChangePassword {
            get {
                return ResourceManager.GetString("ButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Database 的本地化字符串。
        /// </summary>
        internal static string ButtonCreateDatabase {
            get {
                return ResourceManager.GetString("ButtonCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Table With Sql Script 的本地化字符串。
        /// </summary>
        internal static string ButtonCreateSimpleTable {
            get {
                return ResourceManager.GetString("ButtonCreateSimpleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Table With UI 的本地化字符串。
        /// </summary>
        internal static string ButtonCreateTableWithUI {
            get {
                return ResourceManager.GetString("ButtonCreateTableWithUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect ... 的本地化字符串。
        /// </summary>
        internal static string ButtonDetect {
            get {
                return ResourceManager.GetString("ButtonDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Example 的本地化字符串。
        /// </summary>
        internal static string ButtonOpenExample {
            get {
                return ResourceManager.GetString("ButtonOpenExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open History 的本地化字符串。
        /// </summary>
        internal static string ButtonOpenHistory {
            get {
                return ResourceManager.GetString("ButtonOpenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync 的本地化字符串。
        /// </summary>
        internal static string ButtonSync {
            get {
                return ResourceManager.GetString("ButtonSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the last tab, can&apos;t close it 的本地化字符串。
        /// </summary>
        internal static string CannotCloseTabItemNotifyMsg {
            get {
                return ResourceManager.GetString("CannotCloseTabItemNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t parse this sql command 的本地化字符串。
        /// </summary>
        internal static string CannotParseSqlCmdNotifyMsg {
            get {
                return ResourceManager.GetString("CannotParseSqlCmdNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password change successful 的本地化字符串。
        /// </summary>
        internal static string ChangePwdOK {
            get {
                return ResourceManager.GetString("ChangePwdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect in read-only mode 的本地化字符串。
        /// </summary>
        internal static string CheckBoxConnectReadOnly {
            get {
                return ResourceManager.GetString("CheckBoxConnectReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Encrypted 的本地化字符串。
        /// </summary>
        internal static string CheckBoxEncrypt {
            get {
                return ResourceManager.GetString("CheckBoxEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Unicode 的本地化字符串。
        /// </summary>
        internal static string CheckBoxIsUnicode {
            get {
                return ResourceManager.GetString("CheckBoxIsUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically commit changes 的本地化字符串。
        /// </summary>
        internal static string ChkIsAutoCommit {
            get {
                return ResourceManager.GetString("ChkIsAutoCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically shut down 的本地化字符串。
        /// </summary>
        internal static string ChkIsAutoShutdown {
            get {
                return ResourceManager.GetString("ChkIsAutoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read-only 的本地化字符串。
        /// </summary>
        internal static string ChkIsReadonly {
            get {
                return ResourceManager.GetString("ChkIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully cleared the history of opened databases 的本地化字符串。
        /// </summary>
        internal static string ClearedOpendHistoryInfo {
            get {
                return ResourceManager.GetString("ClearedOpendHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Us 的本地化字符串。
        /// </summary>
        internal static string CmdAboutUs {
            get {
                return ResourceManager.GetString("CmdAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change database password 的本地化字符串。
        /// </summary>
        internal static string CmdChangeDbPwd {
            get {
                return ResourceManager.GetString("CmdChangeDbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CmdClose {
            get {
                return ResourceManager.GetString("CmdClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Excel to Access 的本地化字符串。
        /// </summary>
        internal static string CmdConvertExcel2Access {
            get {
                return ResourceManager.GetString("CmdConvertExcel2Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download a database file from the internet 的本地化字符串。
        /// </summary>
        internal static string CmdDownloadDbFile {
            get {
                return ResourceManager.GetString("CmdDownloadDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the official Effiproz homepage 的本地化字符串。
        /// </summary>
        internal static string CmdEffiprozHomepage {
            get {
                return ResourceManager.GetString("CmdEffiprozHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute 的本地化字符串。
        /// </summary>
        internal static string CmdExecute {
            get {
                return ResourceManager.GetString("CmdExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the selected table schema 的本地化字符串。
        /// </summary>
        internal static string CmdExportSelectedTableSchema {
            get {
                return ResourceManager.GetString("CmdExportSelectedTableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate a business entity automatically 的本地化字符串。
        /// </summary>
        internal static string CmdGenerateBusinessEntity {
            get {
                return ResourceManager.GetString("CmdGenerateBusinessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate a column schema 的本地化字符串。
        /// </summary>
        internal static string CmdGenerateColumnSchema {
            get {
                return ResourceManager.GetString("CmdGenerateColumnSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate a Linq to sql O/R mapping object 的本地化字符串。
        /// </summary>
        internal static string CmdGenerateLinqOrMap {
            get {
                return ResourceManager.GetString("CmdGenerateLinqOrMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get information about the current database 的本地化字符串。
        /// </summary>
        internal static string CmdGetCurrentDbInfo {
            get {
                return ResourceManager.GetString("CmdGetCurrentDbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get information about the current server 的本地化字符串。
        /// </summary>
        internal static string CmdGetServerInformation {
            get {
                return ResourceManager.GetString("CmdGetServerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Document 的本地化字符串。
        /// </summary>
        internal static string CmdHelpDocument {
            get {
                return ResourceManager.GetString("CmdHelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Command 的本地化字符串。
        /// </summary>
        internal static string CmdLastCommand {
            get {
                return ResourceManager.GetString("CmdLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Command 的本地化字符串。
        /// </summary>
        internal static string CmdNextCommand {
            get {
                return ResourceManager.GetString("CmdNextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offical SQLite forum 的本地化字符串。
        /// </summary>
        internal static string CmdOnlineSqliteForum {
            get {
                return ResourceManager.GetString("CmdOnlineSqliteForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offical MySql forum 的本地化字符串。
        /// </summary>
        internal static string CmdOnlinMySqlForum {
            get {
                return ResourceManager.GetString("CmdOnlinMySqlForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offical SQLCE forum 的本地化字符串。
        /// </summary>
        internal static string CmdOnlinSSCEForum {
            get {
                return ResourceManager.GetString("CmdOnlinSSCEForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open script file 的本地化字符串。
        /// </summary>
        internal static string CmdOpenScript {
            get {
                return ResourceManager.GetString("CmdOpenScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option 的本地化字符串。
        /// </summary>
        internal static string CmdOption {
            get {
                return ResourceManager.GetString("CmdOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset database 的本地化字符串。
        /// </summary>
        internal static string CmdResetDb {
            get {
                return ResourceManager.GetString("CmdResetDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save result of executed command 的本地化字符串。
        /// </summary>
        internal static string CmdSaveResult {
            get {
                return ResourceManager.GetString("CmdSaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save script to file 的本地化字符串。
        /// </summary>
        internal static string CmdSaveScript {
            get {
                return ResourceManager.GetString("CmdSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official Sql Server forum 的本地化字符串。
        /// </summary>
        internal static string CmdSqlServerForum {
            get {
                return ResourceManager.GetString("CmdSqlServerForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Changes 的本地化字符串。
        /// </summary>
        internal static string CmdSubmitChanges {
            get {
                return ResourceManager.GetString("CmdSubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer data from Access file 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromAccess {
            get {
                return ResourceManager.GetString("CmdTransferDataFromAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer data from CSV file 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromCSV {
            get {
                return ResourceManager.GetString("CmdTransferDataFromCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer data from Excel file 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromExcel {
            get {
                return ResourceManager.GetString("CmdTransferDataFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer data from mysql database 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromMysql {
            get {
                return ResourceManager.GetString("CmdTransferDataFromMysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer data from Sql Server 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromSqlServer {
            get {
                return ResourceManager.GetString("CmdTransferDataFromSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfter data from SQLCE to Sql Server 的本地化字符串。
        /// </summary>
        internal static string CmdTransferDataFromSSCE2SqlServer {
            get {
                return ResourceManager.GetString("CmdTransferDataFromSSCE2SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Here is the column item, you can right click it to call some functions such as [Insert Column], [Modify Column], etc. 的本地化字符串。
        /// </summary>
        internal static string ColumnItemUsage {
            get {
                return ResourceManager.GetString("ColumnItemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string ColumnsName {
            get {
                return ResourceManager.GetString("ColumnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to drop this column? 的本地化字符串。
        /// </summary>
        internal static string ConfirmTextDropColumn {
            get {
                return ResourceManager.GetString("ConfirmTextDropColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to drop this index? 的本地化字符串。
        /// </summary>
        internal static string ConfirmTextDropIndex {
            get {
                return ResourceManager.GetString("ConfirmTextDropIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to drop this table? 的本地化字符串。
        /// </summary>
        internal static string ConfirmTextDropTable {
            get {
                return ResourceManager.GetString("ConfirmTextDropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to cascadingly drop the table? 的本地化字符串。
        /// </summary>
        internal static string ConfirmTextDropTableWithCascade {
            get {
                return ResourceManager.GetString("ConfirmTextDropTableWithCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection String 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringHelperButtonContent {
            get {
                return ResourceManager.GetString("ConnectionStringHelperButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to create this database? 的本地化字符串。
        /// </summary>
        internal static string CreateDatabaseNotifyMsg {
            get {
                return ResourceManager.GetString("CreateDatabaseNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation of database successful 的本地化字符串。
        /// </summary>
        internal static string CreateDatabaseOkMsg {
            get {
                return ResourceManager.GetString("CreateDatabaseOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation of table successful 的本地化字符串。
        /// </summary>
        internal static string CreateTableSchmea_CreateTableOkMsg {
            get {
                return ResourceManager.GetString("CreateTableSchmea_CreateTableOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Table 的本地化字符串。
        /// </summary>
        internal static string CreatTableDialogTitle {
            get {
                return ResourceManager.GetString("CreatTableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input table name 的本地化字符串。
        /// </summary>
        internal static string CreatTableSchema_NeedTableName {
            get {
                return ResourceManager.GetString("CreatTableSchema_NeedTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For CSV or Text Files, please click here 的本地化字符串。
        /// </summary>
        internal static string CSVTooltip {
            get {
                return ResourceManager.GetString("CSVTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are now using {0} database  的本地化字符串。
        /// </summary>
        internal static string CurDbMode {
            get {
                return ResourceManager.GetString("CurDbMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Transfer 的本地化字符串。
        /// </summary>
        internal static string DataExchangeButtonContent {
            get {
                return ResourceManager.GetString("DataExchangeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to display the report of the data transfer? 的本地化字符串。
        /// </summary>
        internal static string DataTransfer_ConfirmViewReport {
            get {
                return ResourceManager.GetString("DataTransfer_ConfirmViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently this type is not supported 的本地化字符串。
        /// </summary>
        internal static string DataTransfer_NotSupportDBType {
            get {
                return ResourceManager.GetString("DataTransfer_NotSupportDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to do a data transfer? This will require some time based on the amount of data. 的本地化字符串。
        /// </summary>
        internal static string DataTransferConfrimMsg {
            get {
                return ResourceManager.GetString("DataTransferConfrimMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No table to process 的本地化字符串。
        /// </summary>
        internal static string DataTransferNoTableMsg {
            get {
                return ResourceManager.GetString("DataTransferNoTableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least one table 的本地化字符串。
        /// </summary>
        internal static string DataTransferSelectTableMsg {
            get {
                return ResourceManager.GetString("DataTransferSelectTableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to delete this database? 的本地化字符串。
        /// </summary>
        internal static string DeleteDatabaseNofityMsg {
            get {
                return ResourceManager.GetString("DeleteDatabaseNofityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion of database successful 的本地化字符串。
        /// </summary>
        internal static string DeleteDatabaseOkMsg {
            get {
                return ResourceManager.GetString("DeleteDatabaseOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documenting Database 的本地化字符串。
        /// </summary>
        internal static string DocumentingDbButtonContent {
            get {
                return ResourceManager.GetString("DocumentingDbButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the database schema to an Excel or Xml Document to help you save a lot of time. 的本地化字符串。
        /// </summary>
        internal static string DocumentingDbButtonContentDescription {
            get {
                return ResourceManager.GetString("DocumentingDbButtonContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency Mode 的本地化字符串。
        /// </summary>
        internal static string EmergencyMode {
            get {
                return ResourceManager.GetString("EmergencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already in emergency mode 的本地化字符串。
        /// </summary>
        internal static string EmergencyModeAgain {
            get {
                return ResourceManager.GetString("EmergencyModeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm switching to emergency mode 的本地化字符串。
        /// </summary>
        internal static string EmergencyModeConfirm {
            get {
                return ResourceManager.GetString("EmergencyModeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to emergency mode: You can try this mode if you can&apos;t see the normal listbox on the left side 的本地化字符串。
        /// </summary>
        internal static string EmergencyModeTooltip {
            get {
                return ResourceManager.GetString("EmergencyModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        internal static string EndButtonText {
            get {
                return ResourceManager.GetString("EndButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EffiProz is a lightweight embedded database written entirely in C#. 
        ///EffiProz is available for the .NET, Silverlight, .NET Compact and Windows Phone 7 frameworks.
        ///The database engine features include ACID compliant transactions, In-Memory mode, SQL/PSM stored procedures, Isolated Storage support for Silverlight and a Persistent In-Memory storage layer. 的本地化字符串。
        /// </summary>
        internal static string Entry_Elliproz_Tooltip {
            get {
                return ResourceManager.GetString("Entry_Elliproz_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For FireBird / Interbase, please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_Friebird_Tooltip {
            get {
                return ResourceManager.GetString("Entry_Friebird_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For MySql 5.0 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_MySql_Tooltip {
            get {
                return ResourceManager.GetString("Entry_MySql_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For OleDB databases such as Access, Excel, CSV etc., please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_Oledb_Tooltip {
            get {
                return ResourceManager.GetString("Entry_Oledb_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Oracle 9 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_Oracle_Tooltip {
            get {
                return ResourceManager.GetString("Entry_Oracle_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For SQLite, please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_Sqlite_Tooltip {
            get {
                return ResourceManager.GetString("Entry_Sqlite_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sql Server 2000 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string Entry_SqlServer_Tooltip {
            get {
                return ResourceManager.GetString("Entry_SqlServer_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft SQL Server 2005 Compact Edition is the compact database for rapidly developing applications in both native and managed environments that extend enterprise data management capabilities to desktop applications 的本地化字符串。
        /// </summary>
        internal static string Entry_SSCE_Tooltip {
            get {
                return ResourceManager.GetString("Entry_SSCE_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The example data file is missing, please reinstall the application or contact the publisher. 的本地化字符串。
        /// </summary>
        internal static string ErrorExampleDataLost {
            get {
                return ResourceManager.GetString("ErrorExampleDataLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occured at Row {0}, Index {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo_CreateTableSchemaDialog {
            get {
                return ResourceManager.GetString("ErrorInfo_CreateTableSchemaDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the list of errors in Stored Procedures: 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo_GetSPListError {
            get {
                return ResourceManager.GetString("ErrorInfo_GetSPListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the list of Trigger errors: 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo_GetTriggerListError {
            get {
                return ResourceManager.GetString("ErrorInfo_GetTriggerListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the list of View errors: 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo_GetViewListError {
            get {
                return ResourceManager.GetString("ErrorInfo_GetViewListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to the source database 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg_CannotConnectToSource {
            get {
                return ResourceManager.GetString("ErrorMsg_CannotConnectToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to the target database 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg_CannotConnectToTarget {
            get {
                return ResourceManager.GetString("ErrorMsg_CannotConnectToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t parse your sql command, please check it . 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg_CannotParseSqlCmd {
            get {
                return ResourceManager.GetString("ErrorMsg_CannotParseSqlCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Type 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg_InvalidType {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Type of TreeItem 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg_InvalidTypeOfTreeItem {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidTypeOfTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This table has no identity column to reset 的本地化字符串。
        /// </summary>
        internal static string ErrorNoIdentityColumnToReset {
            get {
                return ResourceManager.GetString("ErrorNoIdentityColumnToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Excel, please click here 的本地化字符串。
        /// </summary>
        internal static string ExcelTooltip {
            get {
                return ResourceManager.GetString("ExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution of Command Successful 的本地化字符串。
        /// </summary>
        internal static string ExeCmdOKNotifyMsg {
            get {
                return ResourceManager.GetString("ExeCmdOKNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute sql command with no result. 的本地化字符串。
        /// </summary>
        internal static string ExecuteCmdWithNoResult {
            get {
                return ResourceManager.GetString("ExecuteCmdWithNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute Command OK 的本地化字符串。
        /// </summary>
        internal static string ExecuteCmdWithResultOK {
            get {
                return ResourceManager.GetString("ExecuteCmdWithResultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to completely exit the application? 的本地化字符串。
        /// </summary>
        internal static string ExitAppConfirmMsg {
            get {
                return ResourceManager.GetString("ExitAppConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firebird is a relational database offering many ANSI SQL standard features that runs on Linux, Windows, and a variety of Unix platforms. Firebird offers excellent concurrency, high performance and powerful language support for stored procedures and triggers. It has been used in production systems, under a variety of names, since 1981. 的本地化字符串。
        /// </summary>
        internal static string FirebirdTooltip {
            get {
                return ResourceManager.GetString("FirebirdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please close your previous database management page, then try again 的本地化字符串。
        /// </summary>
        internal static string GenerateCoreEAError {
            get {
                return ResourceManager.GetString("GenerateCoreEAError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to generate the linq data context? 的本地化字符串。
        /// </summary>
        internal static string GenerateLinqFileConfrimMsg {
            get {
                return ResourceManager.GetString("GenerateLinqFileConfrimMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to generate the linq data context of the currently opened database? 的本地化字符串。
        /// </summary>
        internal static string GenerateLinqFileConfrimMsg_ForCurrent {
            get {
                return ResourceManager.GetString("GenerateLinqFileConfrimMsg_ForCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated Table Schema succesfully. 的本地化字符串。
        /// </summary>
        internal static string GenerateTableSchemaOK {
            get {
                return ResourceManager.GetString("GenerateTableSchemaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Started 的本地化字符串。
        /// </summary>
        internal static string GettingStartButtonContent {
            get {
                return ResourceManager.GetString("GettingStartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing data from \r\n{0} \r\ninto \r\n{1} \r\nsuccessful. 的本地化字符串。
        /// </summary>
        internal static string ImportAccess_DoOK {
            get {
                return ResourceManager.GetString("ImportAccess_DoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select both the source file and the target file 的本地化字符串。
        /// </summary>
        internal static string ImportAccess_SelectFile {
            get {
                return ResourceManager.GetString("ImportAccess_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation of an SQLCE database failed, this action will be canceled 的本地化字符串。
        /// </summary>
        internal static string ImportData_CreateSSCEFileFailure {
            get {
                return ResourceManager.GetString("ImportData_CreateSSCEFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target file is not existing, this action will be canceled 的本地化字符串。
        /// </summary>
        internal static string ImportData_FileNotFound {
            get {
                return ResourceManager.GetString("ImportData_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This access database has no tables, this action will be canceled 的本地化字符串。
        /// </summary>
        internal static string ImportData_NoTable {
            get {
                return ResourceManager.GetString("ImportData_NoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read access database, this action will be canceled 的本地化字符串。
        /// </summary>
        internal static string ImportData_ReadError {
            get {
                return ResourceManager.GetString("ImportData_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input each element 的本地化字符串。
        /// </summary>
        internal static string ImportEachElement {
            get {
                return ResourceManager.GetString("ImportEachElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please look at the table list and select an item first 的本地化字符串。
        /// </summary>
        internal static string ImportNeedSelectTables {
            get {
                return ResourceManager.GetString("ImportNeedSelectTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indexes 的本地化字符串。
        /// </summary>
        internal static string IndexesName {
            get {
                return ResourceManager.GetString("IndexesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Here is the index item, you can right click it to call some functions such as [Insert Column], [Create Index], etc. 的本地化字符串。
        /// </summary>
        internal static string IndexItemUsage {
            get {
                return ResourceManager.GetString("IndexItemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to back up the database? This action might take a lot of time depending on the size of the database. 的本地化字符串。
        /// </summary>
        internal static string InfoBackupDb {
            get {
                return ResourceManager.GetString("InfoBackupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database backup successful. 的本地化字符串。
        /// </summary>
        internal static string InfoBackupSuccesful {
            get {
                return ResourceManager.GetString("InfoBackupSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A table with this name is already existing, please change it and try again 的本地化字符串。
        /// </summary>
        internal static string InfoTableNameExisted {
            get {
                return ResourceManager.GetString("InfoTableNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the sql command first 的本地化字符串。
        /// </summary>
        internal static string InputSqlCommandNotifyMsg {
            get {
                return ResourceManager.GetString("InputSqlCommandNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid sql command 的本地化字符串。
        /// </summary>
        internal static string InvalidSqlCmdNotifyMsg {
            get {
                return ResourceManager.GetString("InvalidSqlCmdNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charset 的本地化字符串。
        /// </summary>
        internal static string LabelCharset {
            get {
                return ResourceManager.GetString("LabelCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse the tree view 的本地化字符串。
        /// </summary>
        internal static string LabelCollapseTreeView {
            get {
                return ResourceManager.GetString("LabelCollapseTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compact DB 的本地化字符串。
        /// </summary>
        internal static string LabelCompactDB {
            get {
                return ResourceManager.GetString("LabelCompactDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection String 的本地化字符串。
        /// </summary>
        internal static string LabelConnectionString {
            get {
                return ResourceManager.GetString("LabelConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coordinator 的本地化字符串。
        /// </summary>
        internal static string LabelCoordinator {
            get {
                return ResourceManager.GetString("LabelCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Full Path 的本地化字符串。
        /// </summary>
        internal static string LabelDatabaseFullPath {
            get {
                return ResourceManager.GetString("LabelDatabaseFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Type 的本地化字符串。
        /// </summary>
        internal static string LabelDatabaseType {
            get {
                return ResourceManager.GetString("LabelDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data exchange 的本地化字符串。
        /// </summary>
        internal static string LabelDataExchange {
            get {
                return ResourceManager.GetString("LabelDataExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Exchange Wizard 的本地化字符串。
        /// </summary>
        internal static string LabelDataExchangeWizard {
            get {
                return ResourceManager.GetString("LabelDataExchangeWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default View 的本地化字符串。
        /// </summary>
        internal static string LabelDefaultView {
            get {
                return ResourceManager.GetString("LabelDefaultView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer 的本地化字符串。
        /// </summary>
        internal static string LabelDeveloper {
            get {
                return ResourceManager.GetString("LabelDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development Team 的本地化字符串。
        /// </summary>
        internal static string LabelDevTeam {
            get {
                return ResourceManager.GetString("LabelDevTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypt 的本地化字符串。
        /// </summary>
        internal static string LabelEncrypt {
            get {
                return ResourceManager.GetString("LabelEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand the tree view 的本地化字符串。
        /// </summary>
        internal static string LabelExpandTreeView {
            get {
                return ResourceManager.GetString("LabelExpandTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string LabelGeneral {
            get {
                return ResourceManager.GetString("LabelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphic Designer 的本地化字符串。
        /// </summary>
        internal static string LabelGraphicDesigner {
            get {
                return ResourceManager.GetString("LabelGraphicDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Database Size 的本地化字符串。
        /// </summary>
        internal static string LabelMaxDbSize {
            get {
                return ResourceManager.GetString("LabelMaxDbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open CSV File 的本地化字符串。
        /// </summary>
        internal static string LabelOpenCSVFile {
            get {
                return ResourceManager.GetString("LabelOpenCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mode 的本地化字符串。
        /// </summary>
        internal static string LabelOpenMode {
            get {
                return ResourceManager.GetString("LabelOpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select SQLite File 的本地化字符串。
        /// </summary>
        internal static string LabelOpenSqliteFile {
            get {
                return ResourceManager.GetString("LabelOpenSqliteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Access File 的本地化字符串。
        /// </summary>
        internal static string LabelSelectAccessFile {
            get {
                return ResourceManager.GetString("LabelSelectAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Excel File 的本地化字符串。
        /// </summary>
        internal static string LabelSelectExcelFile {
            get {
                return ResourceManager.GetString("LabelSelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address 的本地化字符串。
        /// </summary>
        internal static string LabelServerAddress {
            get {
                return ResourceManager.GetString("LabelServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP (host name) 的本地化字符串。
        /// </summary>
        internal static string LabelServerIpOrHost {
            get {
                return ResourceManager.GetString("LabelServerIpOrHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SID 的本地化字符串。
        /// </summary>
        internal static string LabelSID {
            get {
                return ResourceManager.GetString("LabelSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special 的本地化字符串。
        /// </summary>
        internal static string LabelSpecial {
            get {
                return ResourceManager.GetString("LabelSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        internal static string LabelTool {
            get {
                return ResourceManager.GetString("LabelTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directly use a connection string 的本地化字符串。
        /// </summary>
        internal static string LabelUseConnectionStringDirectly {
            get {
                return ResourceManager.GetString("LabelUseConnectionStringDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string LabelView {
            get {
                return ResourceManager.GetString("LabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        internal static string Language_AutoDetect {
            get {
                return ResourceManager.GetString("Language_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dutch 的本地化字符串。
        /// </summary>
        internal static string Language_Dutch {
            get {
                return ResourceManager.GetString("Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        internal static string Language_Italy {
            get {
                return ResourceManager.GetString("Language_Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        internal static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        internal static string LanguageSelection_AutoDetect {
            get {
                return ResourceManager.GetString("LanguageSelection_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Table 的本地化字符串。
        /// </summary>
        internal static string ModifyTableDialogTitle {
            get {
                return ResourceManager.GetString("ModifyTableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For MySql 5.0 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string MySqlTooltip {
            get {
                return ResourceManager.GetString("MySqlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Sql Command 的本地化字符串。
        /// </summary>
        internal static string NewSqlCommandTabHeader {
            get {
                return ResourceManager.GetString("NewSqlCommandTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result View 的本地化字符串。
        /// </summary>
        internal static string NewTabItemHeader {
            get {
                return ResourceManager.GetString("NewTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No identity column to reset 的本地化字符串。
        /// </summary>
        internal static string NoDataToProcess {
            get {
                return ResourceManager.GetString("NoDataToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not complete, please wait for the next release 的本地化字符串。
        /// </summary>
        internal static string NotCompletedFeatureNotifyMsg {
            get {
                return ResourceManager.GetString("NotCompletedFeatureNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you confirm to exit without submitting your changes?
        ///Effiproz needs to call submit change to save the data that you have changed. 的本地化字符串。
        /// </summary>
        internal static string NotifyMsgBeforeExit {
            get {
                return ResourceManager.GetString("NotifyMsgBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to exit this mode? 的本地化字符串。
        /// </summary>
        internal static string NotifyWhenExitMode {
            get {
                return ResourceManager.GetString("NotifyWhenExitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not complete, please wait for the next release 的本地化字符串。
        /// </summary>
        internal static string NotifyWhenThisFeatureNotCompleted {
            get {
                return ResourceManager.GetString("NotifyWhenThisFeatureNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For OleDB based types, such as Access or Excel c, please click here 的本地化字符串。
        /// </summary>
        internal static string OleDBTooltip {
            get {
                return ResourceManager.GetString("OleDBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to browse the online sql server forum page? 的本地化字符串。
        /// </summary>
        internal static string OnlineRequestMsg_ForSqlServer {
            get {
                return ResourceManager.GetString("OnlineRequestMsg_ForSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to browse the online MySql forum page? 的本地化字符串。
        /// </summary>
        internal static string OnlineRequestMsg_MySql {
            get {
                return ResourceManager.GetString("OnlineRequestMsg_MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to browse the online SQLite forum page? 的本地化字符串。
        /// </summary>
        internal static string OnlineRequestMsg_Sqlite {
            get {
                return ResourceManager.GetString("OnlineRequestMsg_Sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to browse the online SQLCE forum page? 的本地化字符串。
        /// </summary>
        internal static string OnlineRequestMsg_SSCE {
            get {
                return ResourceManager.GetString("OnlineRequestMsg_SSCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Most Recent File 的本地化字符串。
        /// </summary>
        internal static string OpenLatestSqlCEDb {
            get {
                return ResourceManager.GetString("OpenLatestSqlCEDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Oracle 9 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string OracleTooltip {
            get {
                return ResourceManager.GetString("OracleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output file {0} is already existing.\r\nDo you want to delete it and generate it again? 的本地化字符串。
        /// </summary>
        internal static string OverrideFileConfrmMsg {
            get {
                return ResourceManager.GetString("OverrideFileConfrmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The two passwords do not match, please check and try again 的本地化字符串。
        /// </summary>
        internal static string PwdNotEqual {
            get {
                return ResourceManager.GetString("PwdNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data 的本地化字符串。
        /// </summary>
        internal static string QueryWithNoDataResultNotifyMsg {
            get {
                return ResourceManager.GetString("QueryWithNoDataResultNotifyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string ResChooseLanguage {
            get {
                return ResourceManager.GetString("ResChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut 的本地化字符串。
        /// </summary>
        internal static string ResChooseQuickFuncation {
            get {
                return ResourceManager.GetString("ResChooseQuickFuncation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skin 的本地化字符串。
        /// </summary>
        internal static string ResChooseSkin {
            get {
                return ResourceManager.GetString("ResChooseSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to RESET (i.e. Clear/Delete all the data) the currently opened database?\r\nThis action may be a risk, do you really want to do that? 的本地化字符串。
        /// </summary>
        internal static string ResetDataConfrimMsg {
            get {
                return ResourceManager.GetString("ResetDataConfrimMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to RESET (i.e. Clear/Delete all the data) the currently opened database?\r\nThis action may be a risk, do you really want to do that? 的本地化字符串。
        /// </summary>
        internal static string ResetDataCurrentFileConfrimMsg {
            get {
                return ResourceManager.GetString("ResetDataCurrentFileConfrimMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resetting data succesful. 的本地化字符串。
        /// </summary>
        internal static string ResetDataOK {
            get {
                return ResourceManager.GetString("ResetDataOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema Result Info 的本地化字符串。
        /// </summary>
        internal static string SchemaResultInfoHeader {
            get {
                return ResourceManager.GetString("SchemaResultInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an SQLCE DB file first 的本地化字符串。
        /// </summary>
        internal static string SelectSSCEFileMsg {
            get {
                return ResourceManager.GetString("SelectSSCEFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the location for the target file 的本地化字符串。
        /// </summary>
        internal static string SelectTargetMsg {
            get {
                return ResourceManager.GetString("SelectTargetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure that the target location is an existing directory 的本地化字符串。
        /// </summary>
        internal static string SelectToaDirConfirmMsg {
            get {
                return ResourceManager.GetString("SelectToaDirConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stored Procedures 的本地化字符串。
        /// </summary>
        internal static string SpName {
            get {
                return ResourceManager.GetString("SpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine. SQLite is the most widely deployed SQL database engine in the world 的本地化字符串。
        /// </summary>
        internal static string SqliteTooltip {
            get {
                return ResourceManager.GetString("SqliteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The engine execution file is missing, please reinstall 的本地化字符串。
        /// </summary>
        internal static string SqlMetalFileLost {
            get {
                return ResourceManager.GetString("SqlMetalFileLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sql Server 2000 or above, please click here 的本地化字符串。
        /// </summary>
        internal static string SqlServerTooltip {
            get {
                return ResourceManager.GetString("SqlServerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit OK 的本地化字符串。
        /// </summary>
        internal static string SubmitChangesOK {
            get {
                return ResourceManager.GetString("SubmitChangesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Viewers 的本地化字符串。
        /// </summary>
        internal static string SysSchemaViews {
            get {
                return ResourceManager.GetString("SysSchemaViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the table item, you can right click it to call some functions such as [Insert Column], [Create Table], etc. 的本地化字符串。
        /// </summary>
        internal static string TableItemUsage {
            get {
                return ResourceManager.GetString("TableItemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Location 的本地化字符串。
        /// </summary>
        internal static string TextDbLocation {
            get {
                return ResourceManager.GetString("TextDbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Name 的本地化字符串。
        /// </summary>
        internal static string TextDbName {
            get {
                return ResourceManager.GetString("TextDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query time:  的本地化字符串。
        /// </summary>
        internal static string TextQueryCostTime {
            get {
                return ResourceManager.GetString("TextQueryCostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string TilteUpdate {
            get {
                return ResourceManager.GetString("TilteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No sql server instance detected 的本地化字符串。
        /// </summary>
        internal static string TitileNoSqlServerInstanceName {
            get {
                return ResourceManager.GetString("TitileNoSqlServerInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Column 的本地化字符串。
        /// </summary>
        internal static string TitleAddColumn {
            get {
                return ResourceManager.GetString("TitleAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically backup the old DB file version before upgrading (only for SQLCE) 的本地化字符串。
        /// </summary>
        internal static string TitleBkDbAuto {
            get {
                return ResourceManager.GetString("TitleBkDbAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new table name cannot be empty 的本地化字符串。
        /// </summary>
        internal static string TitleCanNotEmptyNewTableName {
            get {
                return ResourceManager.GetString("TitleCanNotEmptyNewTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to change the password 的本地化字符串。
        /// </summary>
        internal static string TitleChangePasswordFailed {
            get {
                return ResourceManager.GetString("TitleChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully changed the password 的本地化字符串。
        /// </summary>
        internal static string TitleChangePasswordSuccessful {
            get {
                return ResourceManager.GetString("TitleChangePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the opened database history information 的本地化字符串。
        /// </summary>
        internal static string TitleClearDBOpendHistoryInfo {
            get {
                return ResourceManager.GetString("TitleClearDBOpendHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Functions 的本地化字符串。
        /// </summary>
        internal static string TitleColumnTab {
            get {
                return ResourceManager.GetString("TitleColumnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documenting database completed successfully 的本地化字符串。
        /// </summary>
        internal static string TitleCompleteDocDbOK {
            get {
                return ResourceManager.GetString("TitleCompleteDocDbOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy column name 的本地化字符串。
        /// </summary>
        internal static string TitleCopyColumnName {
            get {
                return ResourceManager.GetString("TitleCopyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully copied the table and the data. 的本地化字符串。
        /// </summary>
        internal static string TitleCopyDataSuccessful {
            get {
                return ResourceManager.GetString("TitleCopyDataSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy table 的本地化字符串。
        /// </summary>
        internal static string TitleCopyTable {
            get {
                return ResourceManager.GetString("TitleCopyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy table name 的本地化字符串。
        /// </summary>
        internal static string TitleCopyTableName {
            get {
                return ResourceManager.GetString("TitleCopyTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create index 的本地化字符串。
        /// </summary>
        internal static string TitleCreateIndex {
            get {
                return ResourceManager.GetString("TitleCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop column 的本地化字符串。
        /// </summary>
        internal static string TitleDropColumn {
            get {
                return ResourceManager.GetString("TitleDropColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop index 的本地化字符串。
        /// </summary>
        internal static string TitleDropIndex {
            get {
                return ResourceManager.GetString("TitleDropIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop table 的本地化字符串。
        /// </summary>
        internal static string TitleDropTable {
            get {
                return ResourceManager.GetString("TitleDropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute stored procedure 的本地化字符串。
        /// </summary>
        internal static string TitleExecuteSP {
            get {
                return ResourceManager.GetString("TitleExecuteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First row is column name 的本地化字符串。
        /// </summary>
        internal static string TitleFirstRowIsColumnName {
            get {
                return ResourceManager.GetString("TitleFirstRowIsColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of Functions 的本地化字符串。
        /// </summary>
        internal static string TitleFunctionList {
            get {
                return ResourceManager.GetString("TitleFunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Create Script 的本地化字符串。
        /// </summary>
        internal static string TitleGenerateCreateScript {
            get {
                return ResourceManager.GetString("TitleGenerateCreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Create Script For All Tables 的本地化字符串。
        /// </summary>
        internal static string TitleGenerateCreateScriptAll {
            get {
                return ResourceManager.GetString("TitleGenerateCreateScriptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Script 的本地化字符串。
        /// </summary>
        internal static string TitleGenerateScript {
            get {
                return ResourceManager.GetString("TitleGenerateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get info about all columns 的本地化字符串。
        /// </summary>
        internal static string TitleGetColumnInfo {
            get {
                return ResourceManager.GetString("TitleGetColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get info about all Indexes 的本地化字符串。
        /// </summary>
        internal static string TitleGetIndexesInfo {
            get {
                return ResourceManager.GetString("TitleGetIndexesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get supported types 的本地化字符串。
        /// </summary>
        internal static string TitleGetSupportedType {
            get {
                return ResourceManager.GetString("TitleGetSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Functions 的本地化字符串。
        /// </summary>
        internal static string TitleIndexTab {
            get {
                return ResourceManager.GetString("TitleIndexTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the database 的本地化字符串。
        /// </summary>
        internal static string TitleInputDbFile {
            get {
                return ResourceManager.GetString("TitleInputDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string TitleInsert {
            get {
                return ResourceManager.GetString("TitleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert a row 的本地化字符串。
        /// </summary>
        internal static string TitleInsertARow {
            get {
                return ResourceManager.GetString("TitleInsertARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify column 的本地化字符串。
        /// </summary>
        internal static string TitleModifyColumn {
            get {
                return ResourceManager.GetString("TitleModifyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify table schema 的本地化字符串。
        /// </summary>
        internal static string TitleModifyTableSchema {
            get {
                return ResourceManager.GetString("TitleModifyTableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New password 的本地化字符串。
        /// </summary>
        internal static string TitleNewPwd {
            get {
                return ResourceManager.GetString("TitleNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New SQLite File 的本地化字符串。
        /// </summary>
        internal static string TitleNewSqliteFile {
            get {
                return ResourceManager.GetString("TitleNewSqliteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office 2007 format 的本地化字符串。
        /// </summary>
        internal static string TitleOleDBVersion {
            get {
                return ResourceManager.GetString("TitleOleDBVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can double-click the item listed below to open it in the Sql Server Entry UI 的本地化字符串。
        /// </summary>
        internal static string TiTleOpenSqlServerInstanceWay {
            get {
                return ResourceManager.GetString("TiTleOpenSqlServerInstanceWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Populate Sql Server Instance 的本地化字符串。
        /// </summary>
        internal static string TitlePopulateSqlServerInstance {
            get {
                return ResourceManager.GetString("TitlePopulateSqlServerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Link 的本地化字符串。
        /// </summary>
        internal static string TitleQuickLink {
            get {
                return ResourceManager.GetString("TitleQuickLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh column 的本地化字符串。
        /// </summary>
        internal static string TitleRefreshColumn {
            get {
                return ResourceManager.GetString("TitleRefreshColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh index 的本地化字符串。
        /// </summary>
        internal static string TitleRefreshIndex {
            get {
                return ResourceManager.GetString("TitleRefreshIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh system view 的本地化字符串。
        /// </summary>
        internal static string TitleRefreshSystemView {
            get {
                return ResourceManager.GetString("TitleRefreshSystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the ip address or server name to search 的本地化字符串。
        /// </summary>
        internal static string TitleRemoteAddressOrName {
            get {
                return ResourceManager.GetString("TitleRemoteAddressOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename column 的本地化字符串。
        /// </summary>
        internal static string TitleRenameColumn {
            get {
                return ResourceManager.GetString("TitleRenameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename table 的本地化字符串。
        /// </summary>
        internal static string TitleRenameTable {
            get {
                return ResourceManager.GetString("TitleRenameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string TitleReset {
            get {
                return ResourceManager.GetString("TitleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset the identity column 的本地化字符串。
        /// </summary>
        internal static string TitleResetIdentityColumn {
            get {
                return ResourceManager.GetString("TitleResetIdentityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Sql Server Instance 的本地化字符串。
        /// </summary>
        internal static string TitleSearchSqlServerInstance {
            get {
                return ResourceManager.GetString("TitleSearchSqlServerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select.... 的本地化字符串。
        /// </summary>
        internal static string TitleSelect {
            get {
                return ResourceManager.GetString("TitleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        internal static string TitleSelectAll {
            get {
                return ResourceManager.GetString("TitleSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select source database or file 的本地化字符串。
        /// </summary>
        internal static string TitleSelectSrcData {
            get {
                return ResourceManager.GetString("TitleSelectSrcData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select source database type 的本地化字符串。
        /// </summary>
        internal static string TitleSelectSrcDataType {
            get {
                return ResourceManager.GetString("TitleSelectSrcDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the source tables 的本地化字符串。
        /// </summary>
        internal static string TitleSelectSrcTabels {
            get {
                return ResourceManager.GetString("TitleSelectSrcTabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target database or file 的本地化字符串。
        /// </summary>
        internal static string TitleSelectTargetData {
            get {
                return ResourceManager.GetString("TitleSelectTargetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target database type 的本地化字符串。
        /// </summary>
        internal static string TitleSelectTargetDataType {
            get {
                return ResourceManager.GetString("TitleSelectTargetDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select with UI 的本地化字符串。
        /// </summary>
        internal static string TitleSelectWithUI {
            get {
                return ResourceManager.GetString("TitleSelectWithUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show system view data 的本地化字符串。
        /// </summary>
        internal static string TitleShowSystemViewData {
            get {
                return ResourceManager.GetString("TitleShowSystemViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SP Functions 的本地化字符串。
        /// </summary>
        internal static string TitleSpTab {
            get {
                return ResourceManager.GetString("TitleSpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sql Command text font size 的本地化字符串。
        /// </summary>
        internal static string TitleSqlTextFontSize {
            get {
                return ResourceManager.GetString("TitleSqlTextFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source database or file is  的本地化字符串。
        /// </summary>
        internal static string TitleSrcDataFileIs {
            get {
                return ResourceManager.GetString("TitleSrcDataFileIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Functions 的本地化字符串。
        /// </summary>
        internal static string TitleTableTab {
            get {
                return ResourceManager.GetString("TitleTableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target database or file is  的本地化字符串。
        /// </summary>
        internal static string TitleTargetDataFileIs {
            get {
                return ResourceManager.GetString("TitleTargetDataFileIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use sound to notify instead of showing a message 的本地化字符串。
        /// </summary>
        internal static string TitleUseVoiceToNotify {
            get {
                return ResourceManager.GetString("TitleUseVoiceToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View stored procedure code 的本地化字符串。
        /// </summary>
        internal static string TitleViewSP {
            get {
                return ResourceManager.GetString("TitleViewSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Preview Region 的本地化字符串。
        /// </summary>
        internal static string TooltipDataPreviewRegion {
            get {
                return ResourceManager.GetString("TooltipDataPreviewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect the SQLCE data file creation version 的本地化字符串。
        /// </summary>
        internal static string TooltipDetectVersion {
            get {
                return ResourceManager.GetString("TooltipDetectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can drag files directly into this text box 的本地化字符串。
        /// </summary>
        internal static string TooltipDragFile {
            get {
                return ResourceManager.GetString("TooltipDragFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right click the tree view  to get more functions 的本地化字符串。
        /// </summary>
        internal static string TooltipRightClick {
            get {
                return ResourceManager.GetString("TooltipRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triggers 的本地化字符串。
        /// </summary>
        internal static string TriggerName {
            get {
                return ResourceManager.GetString("TriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit Website 的本地化字符串。
        /// </summary>
        internal static string VisitOnlineWebsiteButtonContent {
            get {
                return ResourceManager.GetString("VisitOnlineWebsiteButtonContent", resourceCulture);
            }
        }
    }
}
