//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastestOpenedDb {
            get {
                return ((string)(this["LastestOpenedDb"]));
            }
            set {
                this["LastestOpenedDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastestOpenedDbPwd {
            get {
                return ((string)(this["LastestOpenedDbPwd"]));
            }
            set {
                this["LastestOpenedDbPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("History.xml")]
        public string DbHistoryFileName {
            get {
                return ((string)(this["DbHistoryFileName"]));
            }
            set {
                this["DbHistoryFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint StartMainIDEStep {
            get {
                return ((uint)(this["StartMainIDEStep"]));
            }
            set {
                this["StartMainIDEStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DGF12-N1BDU-37875-DN2A")]
        public string MyXceedGridLisencer {
            get {
                return ((string)(this["MyXceedGridLisencer"]));
            }
            set {
                this["MyXceedGridLisencer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help.xml")]
        public string HelpFile {
            get {
                return ((string)(this["HelpFile"]));
            }
            set {
                this["HelpFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseOldStyleProcessBar {
            get {
                return ((bool)(this["IsUseOldStyleProcessBar"]));
            }
            set {
                this["IsUseOldStyleProcessBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11e114111121111111")]
        public string SQLCELicense {
            get {
                return ((string)(this["SQLCELicense"]));
            }
            set {
                this["SQLCELicense"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BusinessEntity")]
        public string MM_NamespaceName {
            get {
                return ((string)(this["MM_NamespaceName"]));
            }
            set {
                this["MM_NamespaceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixBugMode {
            get {
                return ((bool)(this["FixBugMode"]));
            }
            set {
                this["FixBugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoBackupOldVersionFileBeforeUpgrade {
            get {
                return ((bool)(this["AutoBackupOldVersionFileBeforeUpgrade"]));
            }
            set {
                this["AutoBackupOldVersionFileBeforeUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExpressionDark")]
        public string WPFControlThemeName {
            get {
                return ((string)(this["WPFControlThemeName"]));
            }
            set {
                this["WPFControlThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int CmdTextFontSize {
            get {
                return ((int)(this["CmdTextFontSize"]));
            }
            set {
                this["CmdTextFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NewMain")]
        public string StartUrl {
            get {
                return ((string)(this["StartUrl"]));
            }
            set {
                this["StartUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSpeakInsteadOfMsgBox {
            get {
                return ((bool)(this["UseSpeakInsteadOfMsgBox"]));
            }
            set {
                this["UseSpeakInsteadOfMsgBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help\\DBConnectionString.xps")]
        public string ConnectionStringHelpFile {
            get {
                return ((string)(this["ConnectionStringHelpFile"]));
            }
            set {
                this["ConnectionStringHelpFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CurtainAnimation")]
        public string DialogAnimationName {
            get {
                return ((string)(this["DialogAnimationName"]));
            }
            set {
                this["DialogAnimationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ReplaceTraditional2DTo3D {
            get {
                return ((string)(this["ReplaceTraditional2DTo3D"]));
            }
            set {
                this["ReplaceTraditional2DTo3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRTFQueryTextor {
            get {
                return ((bool)(this["UseRTFQueryTextor"]));
            }
            set {
                this["UseRTFQueryTextor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string SqlEditorFontName {
            get {
                return ((string)(this["SqlEditorFontName"]));
            }
            set {
                this["SqlEditorFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float SqlEditorFontSize {
            get {
                return ((float)(this["SqlEditorFontSize"]));
            }
            set {
                this["SqlEditorFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseAdvTextEditor {
            get {
                return ((bool)(this["IsUseAdvTextEditor"]));
            }
            set {
                this["IsUseAdvTextEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sourceforge.net/projects/sqlceviewer/")]
        public string SourceForgeHomePgae {
            get {
                return ((string)(this["SourceForgeHomePgae"]));
            }
            set {
                this["SourceForgeHomePgae"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.seasonstar.net/misc/sqlceviewer/liveupdate.xml")]
        public string LiveUpdateAddress {
            get {
                return ((string)(this["LiveUpdateAddress"]));
            }
            set {
                this["LiveUpdateAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MaxSqlScriptContextLengthForSwitchTextEditor {
            get {
                return ((int)(this["MaxSqlScriptContextLengthForSwitchTextEditor"]));
            }
            set {
                this["MaxSqlScriptContextLengthForSwitchTextEditor"] = value;
            }
        }
    }
}
